
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    YourVendor\ProductSkuConditionModule\Infrastructure\:
        resource: '../../Infrastructure/*'

